apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pifrost.fullname" . }}
type: Opaque
data:
  pihole_token: {{ required "A valid .Values.pifrost.piholeToken is required." .Values.pifrost.piholeToken | b64enc }}