name: CI

on:
  push:
    branches:
      - '*'

jobs:
  docker_publish:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GH_TOKEN }}